/**
 * Generates `app/assets/css/themes.css` from the vendored Omarchy palettes.
 *
 * Omarchy's themes are built for terminals, where a dim comment colour is
 * normal. On the web that fails WCAG AA — not one of the 22 upstream themes
 * passes when mapped naively. So every token is checked against both surfaces
 * and blended toward the foreground until it clears. Tokyo Night needs exactly
 * one token moved, so the themes stay recognisably themselves.
 *
 * Run via `pnpm generate-themes`. Never hand-edit the generated CSS.
 */
import { readFileSync, readdirSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')
const VENDOR = join(ROOT, 'vendor/omarchy-themes')
const OUT = join(ROOT, 'app/assets/css/themes.css')

/** Order matters: it is the order `t` cycles through. */
export const THEME_ORDER = [
  'tokyo-night', 'kanagawa', 'catppuccin', 'gruvbox', 'everforest',
  'osaka-jade', 'matte-black', 'ristretto', 'rose-pine', 'catppuccin-latte',
]

const AA = 4.6 // Target slightly above 4.5 so rounding cannot land us under.

function parseToml(text) {
  const out = {}
  for (const line of text.split('\n')) {
    const m = /^\s*(\w+)\s*=\s*"([^"]*)"/.exec(line)
    if (m) out[m[1]] = m[2]
  }
  return out
}

const rgb = hex => [0, 2, 4].map(i => Number.parseInt(hex.replace('#', '').slice(i, i + 2), 16))
const toHex = ch => `#${ch.map(c => Math.max(0, Math.min(255, Math.round(c))).toString(16).padStart(2, '0')).join('').toUpperCase()}`

function luminance(hex) {
  const linear = rgb(hex).map((c) => {
    const s = c / 255
    return s <= 0.03928 ? s / 12.92 : ((s + 0.055) / 1.055) ** 2.4
  })
  return 0.2126 * linear[0] + 0.7152 * linear[1] + 0.0722 * linear[2]
}

function contrast(a, b) {
  const [hi, lo] = [luminance(a), luminance(b)].sort((x, y) => y - x)
  return (hi + 0.05) / (lo + 0.05)
}

function hue(hex) {
  const [r, g, b] = rgb(hex).map(c => c / 255)
  const max = Math.max(r, g, b); const min = Math.min(r, g, b); const d = max - min
  if (d === 0) return 0
  let h
  if (max === r) h = ((g - b) / d) % 6
  else if (max === g) h = (b - r) / d + 2
  else h = (r - g) / d + 4
  return ((h * 60) + 360) % 360
}

function hueGap(a, b) {
  const d = Math.abs(hue(a) - hue(b)) % 360
  return Math.min(d, 360 - d)
}

/** Blend `color` toward `toward`, then toward pure white/black, until it clears AA. */
function tune(color, bases, toward) {
  if (bases.every(b => contrast(color, b) >= AA)) return color

  const from = rgb(color)
  for (const target of [rgb(toward), luminance(bases[0]) < 0.5 ? [255, 255, 255] : [0, 0, 0]]) {
    for (let i = 1; i <= 100; i++) {
      const t = i / 100
      const candidate = toHex(from.map((c, j) => c + (target[j] - c) * t))
      if (bases.every(b => contrast(candidate, b) >= AA)) return candidate
    }
  }
  return luminance(bases[0]) < 0.5 ? '#FFFFFF' : '#000000'
}

export function generateThemes() {
  const files = readdirSync(VENDOR).filter(f => f.endsWith('.toml'))
  const themes = []

  for (const name of THEME_ORDER) {
    const file = `${name}.toml`
    if (!files.includes(file)) throw new Error(`missing vendored theme: ${file}`)
    const c = parseToml(readFileSync(join(VENDOR, file), 'utf8'))

    const bg = c.background
    const surface = c.lighter_background || c.selection || bg
    const line = c.muted || surface
    const bases = [bg, surface]

    // Link must read as a different hue from the accent, or links vanish into headings.
    const candidates = ['cyan', 'bright_cyan', 'green', 'magenta', 'bright_magenta', 'blue', 'yellow']
      .map(k => c[k]).filter(Boolean)
    const link = candidates.find(x => hueGap(x, c.accent) > 40) || candidates[0] || c.accent

    themes.push({
      name,
      mode: c.mode === 'light' ? 'light' : 'dark',
      tokens: {
        bg: toHex(rgb(bg)),
        surface: toHex(rgb(surface)),
        line: toHex(rgb(line)),
        fg: tune(c.foreground, bases, c.foreground),
        muted: tune(c.dark_foreground, bases, c.foreground),
        accent: tune(c.accent, bases, c.foreground),
        link: tune(link, bases, c.foreground),
        danger: tune(c.red, bases, c.foreground),
      },
    })
  }
  return themes
}

function toCss(themes) {
  const block = t => `:root[data-theme="${t.name}"] {
  color-scheme: ${t.mode};
${Object.entries(t.tokens).map(([k, v]) => `  --${k}: ${v};`).join('\n')}
  --theme-name: "${t.name}";
  --theme-mode: "${t.mode}";
}`

  const dark = themes.find(t => t.mode === 'dark')
  const light = themes.find(t => t.mode === 'light')
  const defaults = t => Object.entries(t.tokens).map(([k, v]) => `  --${k}: ${v};`).join('\n')

  return `/**
 * GENERATED by scripts/generate-themes.mjs — do not edit.
 * Palettes from Omarchy (MIT, (c) David Heinemeier Hansson), tuned to WCAG AA.
 * Regenerate with \`pnpm generate-themes\`.
 */

/* Default before any choice is stored, and the no-JS baseline. */
:root {
  color-scheme: ${dark.mode};
${defaults(dark)}
  --theme-name: "${dark.name}";
  --theme-mode: "${dark.mode}";
}

@media (prefers-color-scheme: light) {
  :root:not([data-theme]) {
    color-scheme: light;
${defaults(light)}
    --theme-name: "${light.name}";
    --theme-mode: "light";
  }
}

${themes.map(block).join('\n\n')}
`
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const themes = generateThemes()
  writeFileSync(OUT, toCss(themes))
  console.log(`[generate-themes] wrote ${themes.length} themes to ${OUT}`)
}
